
//------------------------------------------------------------------------------
// <auto-generated>
// 此文件由T4模板生成，请勿手动修改
// by hoho
// 11/15/2019 15:59:01
// </auto-generated>
//------------------------------------------------------------------------------


using Hos.ScheduleMaster.Core.Models;

namespace Hos.ScheduleMaster.Core.Repository
{
	[ServiceMapTo(typeof(RepositoryFactory))]
    public class RepositoryFactory
    {
        private TaskDbContext _context;

        public RepositoryFactory(TaskDbContext context)
        {
            _context = context;
        }

			 
	public BaseRepository<ServerNodeEntity> ServerNodes => new BaseRepository<ServerNodeEntity>(_context);

		 
	public BaseRepository<SystemConfigEntity> SystemConfigs => new BaseRepository<SystemConfigEntity>(_context);

		 
	public BaseRepository<SystemLogEntity> SystemLogs => new BaseRepository<SystemLogEntity>(_context);

		 
	public BaseRepository<SystemUserEntity> SystemUsers => new BaseRepository<SystemUserEntity>(_context);

		 
	public BaseRepository<TaskEntity> Tasks => new BaseRepository<TaskEntity>(_context);

		 
	public BaseRepository<TaskGuardianEntity> TaskGuardians => new BaseRepository<TaskGuardianEntity>(_context);

		 
	public BaseRepository<TaskLockEntity> TaskLocks => new BaseRepository<TaskLockEntity>(_context);

		 
	public BaseRepository<TaskReferenceEntity> TaskReferences => new BaseRepository<TaskReferenceEntity>(_context);

		 
	public BaseRepository<TaskRunTraceEntity> TaskRunTraces => new BaseRepository<TaskRunTraceEntity>(_context);

	
    }
}
