
//------------------------------------------------------------------------------
// <auto-generated>
// 此文件由T4模板生成，请勿手动修改
// by hoho
// 11/05/2019 16:44:25
// </auto-generated>
//------------------------------------------------------------------------------


using Hos.ScheduleMaster.Core.Models;

namespace Hos.ScheduleMaster.Core.Repository
{
    public class RepositoryFactory
    {
        private IUnitOfWork _unitOfWork;

        public RepositoryFactory(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

			 
	public BaseRepository<ServerNodeEntity> ServerNodes => new BaseRepository<ServerNodeEntity>(_unitOfWork);

		 
	public BaseRepository<SystemConfigEntity> SystemConfigs => new BaseRepository<SystemConfigEntity>(_unitOfWork);

		 
	public BaseRepository<SystemLogEntity> SystemLogs => new BaseRepository<SystemLogEntity>(_unitOfWork);

		 
	public BaseRepository<SystemUserEntity> SystemUsers => new BaseRepository<SystemUserEntity>(_unitOfWork);

		 
	public BaseRepository<TaskEntity> Tasks => new BaseRepository<TaskEntity>(_unitOfWork);

		 
	public BaseRepository<TaskGuardianEntity> TaskGuardians => new BaseRepository<TaskGuardianEntity>(_unitOfWork);

		 
	public BaseRepository<TaskLockEntity> TaskLocks => new BaseRepository<TaskLockEntity>(_unitOfWork);

		 
	public BaseRepository<TaskReferenceEntity> TaskReferences => new BaseRepository<TaskReferenceEntity>(_unitOfWork);

		 
	public BaseRepository<TaskRunTraceEntity> TaskRunTraces => new BaseRepository<TaskRunTraceEntity>(_unitOfWork);

	
    }
}
