
//------------------------------------------------------------------------------
// <auto-generated>
// 此文件由T4模板生成，请勿手动修改
// by hoho
// 11/26/2019 16:36:18
// </auto-generated>
//------------------------------------------------------------------------------


using Hos.ScheduleMaster.Core.Models;

namespace Hos.ScheduleMaster.Core.Repository
{
	[ServiceMapTo(typeof(RepositoryFactory))]
    public class RepositoryFactory
    {
        private SmDbContext _context;

        public RepositoryFactory(SmDbContext context)
        {
            _context = context;
        }

			 
	public BaseRepository<ScheduleEntity> Schedules => new BaseRepository<ScheduleEntity>(_context);

		 
	public BaseRepository<ScheduleKeeperEntity> ScheduleKeepers => new BaseRepository<ScheduleKeeperEntity>(_context);

		 
	public BaseRepository<ScheduleLockEntity> ScheduleLocks => new BaseRepository<ScheduleLockEntity>(_context);

		 
	public BaseRepository<ScheduleReferenceEntity> ScheduleReferences => new BaseRepository<ScheduleReferenceEntity>(_context);

		 
	public BaseRepository<ScheduleTraceEntity> ScheduleTraces => new BaseRepository<ScheduleTraceEntity>(_context);

		 
	public BaseRepository<ServerNodeEntity> ServerNodes => new BaseRepository<ServerNodeEntity>(_context);

		 
	public BaseRepository<SystemConfigEntity> SystemConfigs => new BaseRepository<SystemConfigEntity>(_context);

		 
	public BaseRepository<SystemLogEntity> SystemLogs => new BaseRepository<SystemLogEntity>(_context);

		 
	public BaseRepository<SystemUserEntity> SystemUsers => new BaseRepository<SystemUserEntity>(_context);

	
    }
}
